openapi: 3.0.0
info:
  title: Graph API Plugin to List Domains Registered to the Entra ID Tenant
  description: Use this skill to retrieve a list of domains that have been registed to the Entra ID tenant.
  version: "1.0"
x-metadata:
  name: ListDomains
  displayName: Retrieve custom domain names in Entra ID
  samplePrompts:
    - "List all domains registered in this Entra ID tenant."
    - "What are the custom domains in this tenant?"
    - "Retrieve all domains in Entra ID that are Federated."
    - "What is the primary domain in this Entra ID tenant."
servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph API
paths:
  /domains:
    get:
      summary: Retrieve domains
      description: Retrieve a list of registered to an Entra ID tenant.
      parameters:
        - name: $filter
          in: query
          required: false
          description: An optional OData filter to query specific domain types.
          schema:
            type: string
            example: "principalId eq '12345' or roleDefinitionId eq '67890'"
      responses:
        '200':
          description: A list of domains.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Role assignment ID.
                        principalId:
                          type: string
                          description: The unique ID of the user or group assigned the role.
                        principalType:
                          type: string
                          description: The type of principal (e.g., User, Group).
                        roleDefinitionId:
                          type: string
                          description: The ID of the role definition.
                        directoryScopeId:
                          type: string
                          description: The scope at which the role is assigned.
                        appScopeId:
                          type: string
                          description: The application scope of the role assignment, if any.
        '401':
          description: Unauthorized. Authentication failed or access token is missing.
        '403':
          description: Forbidden. The authenticated user does not have permission to access this resource.
        '404':
          description: No role assignments found or resource not available.
      security:
        - bearerAuth: []
  /roleManagement/directory/roleDefinitions/{roleDefinitionId}:
    get:
      summary: Retrieve details about a specific role
      description: Get detailed information about a specific role definition by its ID.
      parameters:
        - name: roleDefinitionId
          in: path
          required: true
          description: The unique ID of the role definition to retrieve details for.
          schema:
            type: string
      responses:
        '200':
          description: Details about the specified role definition.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique ID of the role definition.
                  displayName:
                    type: string
                    description: The display name of the role.
                  description:
                    type: string
                    description: A description of the role's purpose.
                  isEnabled:
                    type: boolean
                    description: Whether the role definition is enabled.
        '401':
          description: Unauthorized. Authentication failed or access token is missing.
        '403':
          description: Forbidden. The authenticated user does not have permission to access this resource.
        '404':
          description: Role definition not found.
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
